import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "./globals.css";
import { AppContainer, Header, Footer } from "@/src/app/components";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${inter.variable} antialiased`}
      >
        <AppContainer>
          <Header />
          {children}
          <Footer />
        </AppContainer>
      </body>
    </html>
  );
}
